version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17-browsers
    steps:
      - checkout
      - run:
          name: Проверка файлов
          command: |
            ls -la
            [ -f "index.html" ] || (echo "index.html не найден" && exit 1)
            [ -f "styles.css" ] || (echo "styles.css не найден" && exit 1)
            [ -f "script.js" ] || (echo "script.js не найден" && exit 1)

  deploy:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Сборка Docker-образа
          command: |
            docker build -t invoice-app .
      - run:
          name: Сохранение образа
          command: |
            docker save -o invoice-app.tar invoice-app
      - store_artifacts:
          path: invoice-app.tar
          destination: invoice-app

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main